
packages:
  windows:
    productivity:
      # Browsers
      - Google.Chrome
      # Productivity & Organization
      - Obsidian.Obsidian
      - Microsoft.PowerToys
      - Flow-Launcher.Flow-Launcher
      # Communication
      - SlackTechnologies.Slack
      - Discord.Discord
      - OpenWhisperSystems.Signal
      # File Management & Sync
      - Google.GoogleDrive
      - BillStewart.SyncthingWindowsSetup
      # Media & Entertainment
      - TIDALMusicAS.TIDAL
      # Utilities - Essential
      - JAMSoftware.TreeSize.Free
      # Utilities - Advanced
      - Klocman.BulkCrapUninstaller
      - BleachBit.BleachBit
      # Privacy & Security
      - OO-Software.ShutUp10
