name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Claude AI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.anthropic.com
          MODEL: claude-3-5-sonnet-20241022
          LANGUAGE: en
          PROMPT: |
            Review this code focusing on:
            - Chezmoi best practices and template syntax
            - Shell script safety and error handling
            - Cross-platform compatibility (macOS, Linux, Windows)
            - Package management correctness
            - Security issues (no secrets in commits)
