name: Test Linux

on:
  push:
    branches: [main, master]
    paths:
      - 'home/**'
      - '.github/workflows/test-linux.yaml'
  pull_request:
    branches: [main, master]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test deployment from branch
        run: |
          BRANCH="${{ github.head_ref || github.ref_name }}"
          echo "Testing deployment from branch: $BRANCH"
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ github.repository_owner }} --branch="$BRANCH"
