name: Test macOS

on:
  push:
    branches: [main, master]
    paths:
      - 'home/**'
      - '.github/workflows/test-macos.yaml'
  pull_request:
    branches: [main, master]

jobs:
  test-macos:
    runs-on: macos-latest
    env:
      CHEZMOI_VERSION: 2.52.3 #latest  # Change to pin version: e.g., 2.52.3
    
    steps:
      - name: Test deployment from branch
        run: |
          BRANCH="${{ github.head_ref || github.ref_name }}"
          echo "Installing chezmoi version: $CHEZMOI_VERSION"
          echo "Testing deployment from branch: $BRANCH"
          
          if [ "$CHEZMOI_VERSION" = "latest" ]; then
            sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ github.repository_owner }} --branch="$BRANCH" --verbose
          else
            # Detect architecture
            if [[ "$(uname -m)" == "arm64" ]]; then
              ARCH="arm64"
            else
              ARCH="amd64"
            fi
            curl -fsSL "https://github.com/twpayne/chezmoi/releases/download/v${CHEZMOI_VERSION}/chezmoi_${CHEZMOI_VERSION}_darwin_${ARCH}.tar.gz" | tar -xz -C /tmp
            sudo install /tmp/chezmoi /usr/local/bin/
            chezmoi init --apply ${{ github.repository_owner }} --branch="$BRANCH" --verbose
          fi
          
          chezmoi doctor
