name: Weekly E2E Test

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  test-full-setup:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS
    
    runs-on: ${{ matrix.os }}
    name: Full setup test on ${{ matrix.name }}
    
    steps:
      - name: Test one-liner setup (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Testing full setup from main branch on ${{ matrix.name }}"
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ github.repository_owner }}

      - name: Test one-liner setup (Windows)
        if: runner.os == 'Windows'
        run: |
          Write-Host "Testing full setup from main branch on ${{ matrix.name }}"
          $ChezmoiInstallScript = irm -useb https://get.chezmoi.io/ps1
          & ([scriptblock]::Create($ChezmoiInstallScript))
          chezmoi init --apply ${{ github.repository_owner }}
        shell: powershell
