name: Weekly E2E Test

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  test-full-setup:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS
    
    runs-on: ${{ matrix.os }}
    name: Full setup test on ${{ matrix.name }}
    env:
      CHEZMOI_VERSION: latest  # Change to pin version: e.g., 2.52.3
    
    steps:
      - name: Test one-liner setup (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Installing chezmoi version: $CHEZMOI_VERSION"
          echo "Testing full setup from main branch on ${{ matrix.name }}"
          
          if [ "$CHEZMOI_VERSION" = "latest" ]; then
            sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ github.repository_owner }}
          else
            if [[ "${{ runner.os }}" == "macOS" ]]; then
              # Detect architecture for macOS
              if [[ "$(uname -m)" == "arm64" ]]; then
                ARCH="arm64"
              else
                ARCH="amd64"
              fi
              curl -fsSL "https://github.com/twpayne/chezmoi/releases/download/v${CHEZMOI_VERSION}/chezmoi_${CHEZMOI_VERSION}_darwin_${ARCH}.tar.gz" | tar -xz -C /tmp
            else
              # Linux
              curl -fsSL "https://github.com/twpayne/chezmoi/releases/download/v${CHEZMOI_VERSION}/chezmoi_${CHEZMOI_VERSION}_linux_amd64.tar.gz" | tar -xz -C /tmp
            fi
            sudo install /tmp/chezmoi /usr/local/bin/
            chezmoi init --apply ${{ github.repository_owner }}
          fi
          
          chezmoi doctor
          chezmoi managed

      - name: Test one-liner setup (Windows)
        if: runner.os == 'Windows'
        run: |
          Write-Host "Testing full setup from main branch on ${{ matrix.name }}"
          $ChezmoiInstallScript = irm -useb https://get.chezmoi.io/ps1
          & ([scriptblock]::Create($ChezmoiInstallScript)) -BinDir "$env:TEMP\chezmoi"
          $env:PATH = "$env:TEMP\chezmoi;$env:PATH"
          chezmoi init --apply ${{ github.repository_owner }}
        shell: powershell
