name: Validate

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-dotfiles:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS
    
    runs-on: ${{ matrix.os }}
    name: Validate on ${{ matrix.name }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install chezmoi (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin

      - name: Install chezmoi (Windows)
        if: runner.os == 'Windows'
        run: |
          # Download and install chezmoi
          $ChezmoiInstallScript = irm -useb https://get.chezmoi.io/ps1
          & ([scriptblock]::Create($ChezmoiInstallScript)) -BinDir "$env:TEMP\chezmoi"
          
          # Add to PATH for subsequent steps
          echo "$env:TEMP\chezmoi" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - name: Validate chezmoi configuration
        run: |
          chezmoi doctor --source=${{ github.workspace }}

      - name: Check for template errors (dry-run)
        run: |
          chezmoi apply --dry-run --verbose --source=${{ github.workspace }}

      - name: Report validation success
        run: |
          echo "✓ Dotfiles validated successfully on ${{ matrix.name }}"
