name: Validate

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-dotfiles:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS
    
    runs-on: ${{ matrix.os }}
    name: Validate on ${{ matrix.name }}
    env:
      CHEZMOI_VERSION: latest  # Change to pin version: e.g., 2.52.3
    
    steps:
      - name: Test deployment from branch (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          BRANCH="${{ github.head_ref || github.ref_name }}"
          echo "Installing chezmoi version: $CHEZMOI_VERSION"
          echo "Testing deployment on ${{ matrix.name }} from branch: $BRANCH"
          
          if [ "$CHEZMOI_VERSION" = "latest" ]; then
            sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ github.repository_owner }} --branch="$BRANCH" --verbose
          else
            if [[ "${{ runner.os }}" == "macOS" ]]; then
              # Detect architecture for macOS
              if [[ "$(uname -m)" == "arm64" ]]; then
                ARCH="arm64"
              else
                ARCH="amd64"
              fi
              curl -fsSL "https://github.com/twpayne/chezmoi/releases/download/v${CHEZMOI_VERSION}/chezmoi_${CHEZMOI_VERSION}_darwin_${ARCH}.tar.gz" | tar -xz -C /tmp
            else
              # Linux
              curl -fsSL "https://github.com/twpayne/chezmoi/releases/download/v${CHEZMOI_VERSION}/chezmoi_${CHEZMOI_VERSION}_linux_amd64.tar.gz" | tar -xz -C /tmp
            fi
            sudo install /tmp/chezmoi /usr/local/bin/
            chezmoi init --apply ${{ github.repository_owner }} --branch="$BRANCH" --verbose
          fi
          
          chezmoi doctor

      - name: Test deployment from branch (Windows)
        if: runner.os == 'Windows'
        run: |
          $ChezmoiInstallScript = irm -useb https://get.chezmoi.io/ps1
          & ([scriptblock]::Create($ChezmoiInstallScript)) -BinDir "$env:TEMP\chezmoi"
          $env:PATH = "$env:TEMP\chezmoi;$env:PATH"
          
          if ("${{ github.event_name }}" -eq "pull_request") {
            $branch = "${{ github.head_ref }}"
          } else {
            $branch = "${{ github.ref_name }}"
          }
          Write-Host "Testing deployment on ${{ matrix.name }} from branch: $branch"
          chezmoi init --apply ${{ github.repository_owner }} --branch="$branch"
        shell: powershell
