name: Validate

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-dotfiles:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS
    
    runs-on: ${{ matrix.os }}
    name: Validate on ${{ matrix.name }}
    
    steps:
      - name: Test deployment from branch (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          BRANCH="${{ github.head_ref || github.ref_name }}"
          echo "Testing deployment on ${{ matrix.name }} from branch: $BRANCH"
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ github.repository_owner }} --branch="$BRANCH"

      - name: Install chezmoi (Windows)
        if: runner.os == 'Windows'
        run: |
          $ChezmoiInstallScript = irm -useb https://get.chezmoi.io/ps1
          & ([scriptblock]::Create($ChezmoiInstallScript)) -BinDir "$env:TEMP\chezmoi"
          $env:PATH = "$env:TEMP\chezmoi;$env:PATH"
        shell: powershell

      - name: Test deployment from branch (Windows)
        if: runner.os == 'Windows'
        run: |
          if ("${{ github.event_name }}" -eq "pull_request") {
            $branch = "${{ github.head_ref }}"
          } else {
            $branch = "${{ github.ref_name }}"
          }
          Write-Host "Testing deployment on ${{ matrix.name }} from branch: $branch"
          chezmoi init --apply ${{ github.repository_owner }} --branch="$branch"
        shell: powershell
